### ISSUE TITLE
pygame detect.py fails on Dev Board

### ISSUE THREAD

**Issue by scottamain** [google-coral/examples-camera#20]
Running Mendel 4.0:

examples-camera/pygame$ python3 detect.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Loading ../all_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite with ../all_models/coco_labels.txt labels.
Traceback (most recent call last):
  File "detect.py", line 102, in <module>
    main()
  File "detect.py", line 68, in main
    display = pygame.display.set_mode((cam_w, cam_h), 0)
pygame.error: Unable to open a console terminal

**Comment by mtyka** [comment]
Detect.py is looking for a screen.
On DevBoard, when you're starting it over ssh (rather than in a Wayland window) and have a screen attached, do ```export DISPLAY=":0" ``` and then runt he code. Then it will work (just tried on Mendel 4)
I'll update the code to give a better error message to this effect and perhaps an option to just display the detections in console without overlaid bounding boxes.
